version: 2.4

volumes:
  pulse:
  audio-content:

services:

  rfid-reader:
    build: ./rfid-reader
    privileged: true

  audio-player:
    build: ./audio-player
    privileged: true
    volumes:
      - pulse:/run/pulse
      - audio-content:/audio

  server:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - audio-content:/audio

  audio:
    build: ./audio
    privileged: true
    volumes:
      - pulse:/run/pulse
