# yes, this is a container only to deal with the rotary encoder
FROM balenalib/%%BALENA_ARCH%%-node:20-run

WORKDIR /usr/app

RUN install_packages python-is-python3 make g++
# g++ python3-dev git make 

COPY package*.json ./
RUN npm install

COPY gpio.sh .
COPY src/ src/

#dev-cmd-live=npm run watch
CMD [ "npm", "run", "start" ]